### ISSUE TITLE
Library de.ibapl.spsw.jniprovider in version 3.0.1 cannot be used from maven repository because of broken dependence

### ISSUE THREAD

**Issue by david-jezek** [aploese/spsw#4]
Library de.ibapl.spsw.jniprovider in version 3.0.1 cannot be used from maven repository because of depend on goup:'de.ibapl.jnhw', artifact:'de.ibapl.jnhw.libloader', version:'[2.0.0,3.0.0)' but on mvnrepository.com  is published only goup:'de.ibapl.jnhw', artifact:'de.ibapl.jnhw.libloader', version:'1.0.0'

**Comment by aploese** [comment]
Hi,

for the moment you can use the SPSW snapshot 3.1.0-SNAPSHOT
add this snapshot repository to your pom:

    <distributionManagement>
        <snapshotRepository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>

<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

I try to prepare the SPSW 3.1. and JNHW 3.0 release in the next tree
weeks.

Arne


Am Samstag, dem 28.08.2021 um 17:01 -0700 schrieb david-jezek:

**Comment by aploese** [comment]
Fixed in release 3.1.0.
